services:
  - type: web
    name: megz
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn megz.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: megz.settings
      - key: SECRET_KEY
        value: django-insecure-d-_bk-pov5_7v1khvlqp3wfp-b^is@hj&2+-oc&+%p23r@jt83
        
