# Generated by Django 5.1.7 on 2025-03-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
