# Generated by Django 5.1.7 on 2025-03-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_spareentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
