# Generated by Django 5.1.7 on 2025-03-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
