# Generated by Django 5.1.7 on 2025-03-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_adminuser_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='plain_password',
        ),
    ]
