# Generated by Django 5.1.7 on 2025-03-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
