# Generated by Django 5.1.7 on 2025-04-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='colors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
